  
name: prValidation

on: 
  pull_request:
      branches:
        - dev

jobs:
  build:
    name: danger-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Danger JS Action
        uses: danger/danger-js@9.1.8
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
